"""initial schema: sources, raw_items, leads, lead_feedback, keywords

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-15

Hand-written (not autogenerated): this sandbox has no live Postgres to
autogenerate against. DDL mirrors app/models/*.py exactly — cross-check
against those files if you add an autogenerated revision later and see
an unexpected diff.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("external_identifier", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index("ix_sources_type", "sources", ["type"])

    op.create_table(
        "raw_items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "source_id",
            sa.Integer(),
            sa.ForeignKey("sources.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("author_username", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.UniqueConstraint("source_id", "external_id", name="uq_raw_items_source_external_id"),
    )
    op.create_index("ix_raw_items_content_hash", "raw_items", ["content_hash"])

    op.create_table(
        "leads",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "raw_item_id",
            sa.Integer(),
            sa.ForeignKey("raw_items.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("is_lead", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("lead_probability", sa.Float(), nullable=False, server_default="0"),
        sa.Column("lead_score", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("lead_type", sa.String(length=64), nullable=True),
        sa.Column("services", sa.JSON(), nullable=False),
        sa.Column("business_niche", sa.String(length=255), nullable=True),
        sa.Column("project_description", sa.Text(), nullable=True),
        sa.Column("budget_min", sa.Float(), nullable=True),
        sa.Column("budget_max", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("urgency", sa.String(length=16), nullable=True),
        sa.Column("complexity", sa.String(length=16), nullable=True),
        sa.Column("estimated_value", sa.String(length=16), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("positive_signals", sa.JSON(), nullable=False),
        sa.Column("negative_signals", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="new"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index("ix_leads_lead_score", "leads", ["lead_score"])
    op.create_index("ix_leads_status", "leads", ["status"])
    op.create_index("ix_leads_score_status", "leads", ["lead_score", "status"])
    op.create_index("ix_leads_created_at", "leads", ["created_at"])

    op.create_table(
        "lead_feedback",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "lead_id", sa.Integer(), sa.ForeignKey("leads.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("feedback_type", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index("ix_lead_feedback_lead_id", "lead_feedback", ["lead_id"])

    op.create_table(
        "keywords",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("keyword", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False, server_default="1"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.UniqueConstraint("keyword", "category", name="uq_keywords_keyword_category"),
    )
    op.create_index("ix_keywords_keyword", "keywords", ["keyword"])
    op.create_index("ix_keywords_category", "keywords", ["category"])
    op.create_index("ix_keywords_is_active", "keywords", ["is_active"])


def downgrade() -> None:
    op.drop_table("keywords")
    op.drop_table("lead_feedback")
    op.drop_table("leads")
    op.drop_table("raw_items")
    op.drop_table("sources")
